"""Export cookies from a live CDP browser context to a Netscape cookie file.

yt-dlp needs authenticated cookies to read Instagram (and gated Facebook)
content, but it cannot copy Chrome's cookie DB while Chrome is running (it
holds a lock — yt-dlp issue #7271). Since we keep Chrome open for CDP, we
instead read the cookies straight from the authenticated Playwright context
and write them in the Netscape format yt-dlp accepts via --cookies.

One file per platform, refreshed at the start of each scrape run so the
session cookie is always current.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from playwright.async_api import BrowserContext

from .. import config

_DOMAIN_HINT = {"instagram": "instagram", "facebook": "facebook"}


def _to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by meta_osint", ""]
    for ck in cookies:
        domain = ck.get("domain", "")
        if not domain:
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = ck.get("path", "/") or "/"
        secure = "TRUE" if ck.get("secure") else "FALSE"
        raw_exp = ck.get("expires", 0)
        expires = int(raw_exp) if isinstance(raw_exp, (int, float)) and raw_exp > 0 else 0
        name = ck.get("name", "")
        value = ck.get("value", "")
        if not name:
            continue
        lines.append("\t".join([domain, include_sub, path, secure, str(expires), name, value]))
    return "\n".join(lines) + "\n"


def cookie_file_path(platform: str) -> Path:
    return config.DATA_DIR / f"cookies_{platform}.txt"


async def export_cookies(context: BrowserContext, platform: str) -> Optional[str]:
    """Write the platform's cookies from `context` to a Netscape file.

    Returns the file path (str) on success, or None if no relevant cookies
    were found (e.g. not logged in)."""
    try:
        all_cookies = await context.cookies()
    except Exception:
        return None

    hint = _DOMAIN_HINT.get(platform, platform)
    relevant = [c for c in all_cookies if hint in (c.get("domain", "") or "")]
    if not relevant:
        return None

    path = cookie_file_path(platform)
    try:
        path.write_text(_to_netscape(relevant), encoding="utf-8")
    except OSError:
        return None
    return str(path)
