"""Seed category set: strategic / nuclear-security topic taxonomy.

Ported from the client's `priority_topics` table (topic_id, name, weight,
keywords JSON). Kept as Python rather than a .sql file so the same seed loads
on both SQLite and MySQL through the ordinary DB layer, with no import step
and no dialect issues.

`weight` is the batch priority: W3 categories are scraped first, then W2, then
W1. Loading is idempotent - `load_seed_categories` upserts by `code`, so
re-running it updates names/weights/keywords instead of duplicating. Edits made
in the dashboard are preserved unless you pass overwrite=True.
"""
from __future__ import annotations

SEED_CATEGORIES: list[dict] = [
    {
        "code": "a",
        "name": "Nuclear Doctrine, Posture, Developments & Debates",
        "weight": "W2",
        "keywords": [
            "nuclear doctrine",
            "nuclear posture",
            "nuclear posture review",
            "nuclear declaratory policy",
            "nuclear employment policy",
            "nuclear threshold",
            "launch on warning",
            "assured retaliation",
            "nuclear signaling",
            "nuclear escalation",
            "nuclear doctrine revision",
            "doctrinal shift",
            "revised doctrine",
            "new nuclear policy",
        ],
    },
    {
        "code": "b",
        "name": "Nuclear Deterrence",
        "weight": "W2",
        "keywords": [
            "nuclear deterrence",
            "strategic deterrence",
            "full spectrum deterrence",
            "credible minimum deterrence",
            "minimum credible deterrence",
            "second strike capability",
            "deterrence credibility",
            "deterrence stability",
            "extended deterrence",
            "nuclear umbrella",
            "negative security assurance",
            "forward deterrence",
            "tailored deterrence",
            "cross-domain deterrence",
            "escalation dominance",
        ],
    },
    {
        "code": "c",
        "name": "Confidence Building Measures (CBMs)",
        "weight": "W1",
        "keywords": [
            "confidence building measures",
            "CBM",
            "nuclear risk reduction",
            "strategic stability dialogue",
            "crisis communication",
            "military hotline",
            "missile test pre-notification",
            "launch notification",
            "transparency measures",
            "risk reduction measures",
            "Track 1 diplomacy",
            "Track 1.5 dialogue",
            "Track 2 dialogue",
            "backchannel diplomacy",
            "strategic restraint regime",
        ],
    },
    {
        "code": "d",
        "name": "Nuclear Strategy & Force Modernization",
        "weight": "W2",
        "keywords": [
            "nuclear strategy",
            "counterforce",
            "countervalue",
            "counterforce targeting",
            "damage limitation",
            "second strike",
            "survivability",
            "MIRV",
            "multiple independently targetable reentry vehicle",
            "canisterised missile",
            "SSBN",
            "ballistic missile submarine",
            "nuclear triad",
            "sea-based deterrent",
            "force modernization",
            "nuclear modernization",
            "warhead modernization",
            "delivery system modernization",
            "recapitalization",
            "hardened silo",
            "force dispersal",
            "nuclear targeting policy",
        ],
    },
    {
        "code": "e",
        "name": "Missile Tests / MTCR",
        "weight": "W3",
        "keywords": [
            "missile test",
            "ballistic missile test",
            "cruise missile test",
            "hypersonic missile test",
            "missile flight test",
            "test launch",
            "missile launch notification",
            "NOTAM",
            "NAVAREA",
            "missile telemetry",
            "solid fuel missile",
            "liquid fuel missile",
            "TEL",
            "IRBM",
            "MRBM",
            "ICBM",
            "SLBM",
            "reentry vehicle",
            "MTCR",
            "Missile Technology Control Regime",
            "user trial",
        ],
    },
    {
        "code": "f",
        "name": "Nuclear & Missile Export Control Regime",
        "weight": "W2",
        "keywords": [
            "nuclear export controls",
            "missile export controls",
            "strategic trade controls",
            "dual-use export controls",
            "MTCR Category I",
            "MTCR Category II",
            "Nuclear Suppliers Group",
            "NSG guidelines",
            "NSG membership",
            "NSG waiver",
            "Zangger Committee",
            "Wassenaar Arrangement",
            "end-use verification",
            "catch-all controls",
            "export licensing",
            "illicit procurement",
            "proliferation financing",
            "controlled technology transfer",
            "covert procurement",
            "procurement network",
            "front company",
            "sanctions evasion",
            "dual-use procurement",
            "missile proliferation",
            "weapons proliferation",
            "entity list",
        ],
    },
    {
        "code": "g",
        "name": "Arms Control",
        "weight": "W2",
        "keywords": [
            "arms control",
            "nuclear arms control",
            "arms control negotiations",
            "strategic arms reduction",
            "arms limitation",
            "nuclear disarmament",
            "arms control framework",
            "verification regime",
            "treaty compliance",
            "warhead limits",
            "delivery vehicle limits",
            "bilateral arms control",
            "multilateral arms control",
            "arms control dialogue",
            "NPT",
            "Nuclear Non-Proliferation Treaty",
            "NPT RevCon",
            "CTBT",
            "Comprehensive Nuclear-Test-Ban Treaty",
            "FMCT",
            "Fissile Material Cut-off Treaty",
            "New START",
            "INF Treaty",
            "TPNW",
            "Conference on Disarmament",
            "UNODA",
            "UNGA First Committee",
            "UNSCR 1540",
            "1540 Committee",
            "arms control treaty",
            "non-proliferation regime",
        ],
    },
    {
        "code": "h",
        "name": "Nuclear Weapons",
        "weight": "W2",
        "keywords": [
            "nuclear weapons program",
            "nuclear arsenal",
            "nuclear stockpile",
            "warhead",
            "nuclear warhead",
            "warhead estimate",
            "arsenal expansion",
            "uranium enrichment",
            "enrichment capability",
            "highly enriched uranium",
            "HEU",
            "plutonium production",
            "reprocessing",
            "fissile material",
            "fissile material production",
            "weapons-grade",
            "weaponization",
            "nuclear breakout",
            "breakout time",
            "nuclear proliferation",
            "Nuclear Notebook",
            "warhead dismantlement",
        ],
    },
    {
        "code": "i",
        "name": "Missile Defense (BMD)",
        "weight": "W2",
        "keywords": [
            "ballistic missile defense",
            "BMD",
            "missile defence",
            "anti-ballistic missile",
            "ABM",
            "missile interceptor",
            "THAAD",
            "Patriot",
            "Aegis BMD",
            "Arrow missile defense",
            "S-400",
            "Iron Dome",
            "integrated air and missile defense",
            "IAMD",
            "midcourse defense",
            "terminal defense",
            "exo-atmospheric interceptor",
            "hit-to-kill",
            "early warning radar",
            "missile tracking radar",
            "counter-hypersonic defense",
            "missile shield",
        ],
    },
    {
        "code": "j",
        "name": "Defense Acquisitions",
        "weight": "W1",
        "keywords": [
            "defense acquisition",
            "defence procurement",
            "military procurement",
            "arms procurement",
            "weapons acquisition",
            "foreign military sales",
            "FMS",
            "request for proposal",
            "RFP",
            "request for information",
            "RFI",
            "defence tender",
            "contract award",
            "procurement approval",
            "technology transfer",
            "licensed production",
            "offset agreement",
            "delivery schedule",
            "military modernization",
            "co-production",
            "inducted into service",
        ],
    },
    {
        "code": "k",
        "name": "Military Exercises",
        "weight": "W2",
        "keywords": [
            "military exercise",
            "joint military exercise",
            "multinational exercise",
            "strategic exercise",
            "live fire exercise",
            "command post exercise",
            "CPX",
            "field training exercise",
            "FTX",
            "readiness drill",
            "strategic forces exercise",
            "nuclear forces exercise",
            "missile exercise",
            "air defence exercise",
            "naval exercise",
            "mobilization drill",
            "deployment exercise",
            "war game",
        ],
    },
    {
        "code": "l",
        "name": "Arms Race",
        "weight": "W1",
        "keywords": [
            "arms race",
            "nuclear arms race",
            "missile race",
            "arms buildup",
            "military buildup",
            "action-reaction spiral",
            "arms competition",
            "regional balance",
            "strategic balance",
            "balance of power shift",
            "capability gap",
            "matching capability",
            "falling behind",
            "tit for tat",
            "spiralling escalation",
            "security dilemma",
            "stability-instability paradox",
            "defence spending increase",
            "military expenditure growth",
            "in response to",
        ],
    },
    {
        "code": "m",
        "name": "Emerging Technologies (AI / Cyber / Quantum)",
        "weight": "W2",
        "keywords": [
            "emerging technology",
            "military AI",
            "artificial intelligence defense",
            "autonomous weapons",
            "lethal autonomous weapons",
            "LAWS",
            "AI-enabled ISR",
            "AI decision support",
            "human-machine teaming",
            "swarm autonomy",
            "cyber warfare",
            "cyber deterrence",
            "cyber strategic stability",
            "cyberattack",
            "quantum technology",
            "quantum sensing",
            "quantum communications",
            "quantum key distribution",
            "military quantum technology",
            "NC3",
            "nuclear command control and communications",
        ],
    },
    {
        "code": "n",
        "name": "Outer Space",
        "weight": "W1",
        "keywords": [
            "outer space security",
            "space security",
            "military space",
            "counterspace",
            "anti-satellite",
            "ASAT",
            "direct-ascent ASAT",
            "co-orbital capability",
            "space domain awareness",
            "space situational awareness",
            "SSA",
            "space-based ISR",
            "missile warning satellite",
            "early warning satellite",
            "satellite jamming",
            "satellite spoofing",
            "space command",
            "PAROS",
            "space arms control",
            "Outer Space Treaty",
            "space launch vehicle",
        ],
    },
    {
        "code": "o",
        "name": "UAV, Drones, Predators & Counter-Drones",
        "weight": "W1",
        "keywords": [
            "UAV",
            "UAS",
            "UCAV",
            "combat drone",
            "armed UAV",
            "MALE UAV",
            "HALE UAV",
            "loitering munition",
            "one-way attack drone",
            "FPV drone",
            "drone swarm",
            "autonomous drone",
            "ISR drone",
            "Predator drone",
            "MQ-9",
            "Bayraktar",
            "kamikaze drone",
            "counter-UAS",
            "C-UAS",
            "anti-drone",
            "drone jammer",
            "drone detection radar",
            "drone strike",
            "airspace violation by a drone",
        ],
    },
    {
        "code": "p",
        "name": "Nuclear Safety & Security",
        "weight": "W3",
        "keywords": [
            "nuclear safety",
            "nuclear security",
            "IAEA nuclear security",
            "IAEA safeguards",
            "IAEA inspection",
            "nuclear security culture",
            "physical protection nuclear material",
            "nuclear material security",
            "radioactive source security",
            "nuclear facility protection",
            "emergency preparedness",
            "nuclear incident",
            "nuclear accident",
            "CPPNM",
            "Convention on Physical Protection of Nuclear Material",
            "nuclear smuggling",
            "illicit trafficking radioactive material",
            "radiological security",
            "nuclear regulatory authority",
            "insider threat",
            "loose nukes",
            "unsafe arsenal",
        ],
    },
]


def load_seed_categories(db, overwrite: bool = False) -> dict:
    """Insert the seed taxonomy into `db`.

    overwrite=False (default) only creates categories that do not exist yet, so
    a category you have since edited in the dashboard keeps your changes.
    overwrite=True resets every seed category's name, weight and keyword list
    back to the values above.

    Returns {"created": n, "updated": n, "skipped": n, "keywords": n}.
    """
    existing = {c.get("code") for c in db.get_categories()}
    stats = {"created": 0, "updated": 0, "skipped": 0, "keywords": 0}
    for cat in SEED_CATEGORIES:
        if cat["code"] in existing and not overwrite:
            stats["skipped"] += 1
            continue
        db.upsert_category(
            cat["name"], code=cat["code"], weight=cat["weight"],
            enabled=True, keywords=cat["keywords"], replace_keywords=True,
        )
        stats["updated" if cat["code"] in existing else "created"] += 1
        stats["keywords"] += len(cat["keywords"])
    return stats
